//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban
    {
        public int ban_id { get; set; }
        public string ban_reason { get; set; }
        public Nullable<System.DateTime> ban_duration { get; set; }
        public Nullable<System.DateTime> ban_time { get; set; }
        public Nullable<int> u_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
