//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_appoinment
    {
        public doc_appoinment()
        {
            this.patients = new HashSet<patient>();
        }
    
        public int app_id { get; set; }
        public Nullable<int> app_fee { get; set; }
        public string app_status { get; set; }
        public int schedule_id { get; set; }
        public Nullable<int> isdeleted { get; set; }
    
        public virtual doctor_schedule doctor_schedule { get; set; }
        public virtual ICollection<patient> patients { get; set; }
    }
}
