//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.prescriptions = new HashSet<prescription>();
        }
    
        public int p_id { get; set; }
        public string p_sickness_reason { get; set; }
        public string p_diagnostics_info { get; set; }
        public int u_id { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<int> isdeleted { get; set; }
        public string status { get; set; }
    
        public virtual doc_appoinment doc_appoinment { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
